# Generated by Django 4.1.3 on 2022-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_tvparser_title_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvparser',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
