# Generated by Django 4.1.3 on 2022-12-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_alter_tvparser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvparser',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
